### ISSUE TITLE
mysql connexion error + db choice

### ISSUE THREAD

**Issue by julienhmmt** [flemzord/datacube#2]
hello !
when I'm using the datacube script to save my WordPress website, I can't modify the credientials used to connect to the sql server ;
> how is it possible to modify credentials ?

---
can we select just one database to save instead of every database of the sql server ?

**Comment by flemzord** [comment]
Hello Julien,

You can use the script backup_script/mysql-single-base.sh that will allow you to backup a single database it also integrates the connection identifiers.

Maxence

**Comment by julienhmmt** [comment]
Alright, it works with the backup_script/mysql-single-base.sh and the root access ;)
