### ISSUE TITLE
How to update datacube ?

### ISSUE THREAD

**Issue by julienhmmt** [flemzord/datacube#5]
Hello :)
I've installed Datacube service since 2 days and it appears that a new update is here. How to install it ? thanks :)

**Comment by flemzord** [comment]
Hello Julien,

You can cd /opt/datacube && git pull origin master
And sources will be updates.
/! \ There was a very big change, it is imperative to check your configuration

Maxence

**Comment by julienhmmt** [comment]
I've modified my launch.sh because of some custom_scripts. An error appear when I wanted to git pull. To resolve it : 
`cd /opt/datacube && mv launch.sh launch.sh.old && git pull origin master`
It works, Datacube in last version :)
